name: techbistro
description: "Comanda digital para restaurantes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  supabase_flutter: ^2.9.1
  flutter_riverpod: ^2.5.1 
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^6.0.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  printing: ^5.11.0
  pdf: ^3.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
  fonts:
    - family: Nats
      fonts:
        - asset: assets/fonts/NATS-Regular.ttf
